### PR TITLE
Add Docker Compose and update README.md

### PR DESCRIPTION
**Pull request by cwilby**
Hey @Webysther!

I have been using packagist for about a year now, and in that time I've been thinking about ways to fully automate with docker-compose - leading us to this work-in-progress PR!

**Summary of work:**
* Adds Dockerfiles for nginx / php-fpm websyther/composer-debian.  Some of this work is loosely based on the [Laradock](https://laradock.io) project.
* Adds a docker-compose.yml file to setup a packagist mirror running on localhost.
* Adds a docker-compose.prod.yml file to setup a packagist mirror that integrates with traefik.
* Updates the copy in README.md to include new installation instructions, creating a total of three different installation methods.

I'm using this setup on a couple of [traefik](https://traefik.io) enabled hosts, and the process was straight forward after completing this work - so I wanted to present this to you and see if the project can find it useful!

### CODE REVIEW

**Comment by webysther** [comment]
Great job, in the next few days I review the PR! 💃

**Comment by webysther** [comment]
@cwilby Great job, all done! Only a one question: PHP is not need to create a mirror, you use for another motivation?

**Comment by cwilby** [comment]
@webysther the `php-fpm` image serves PHP requests from `nginx`, which hosts the `index.php` generated by the worker container.

I've gone back and forth on whether to have a separate container for php-fpm or a merged nginx-php-fpm container, and I decided to separate so that php-fpm can scale independently of nginx, and vice versa.

**Comment by webysther** [comment]
@cwilby Acctually the product from library is a full static page, you don't need a PHP interpreter to host, only if you have the need for another things.
[Here is the code](https://github.com/webysther/packagist-mirror/blob/08f5d49e8c206eba917475d8e00fe9ef8abab73b/src/Command/Create.php#L465) that update the index.html of mirror, at the end of every creation or update.

Tip: [The nginx server a lot more static pages than dynamic ones.](https://rollout.io/blog/pregenerating-static-web-pages-for-better-performance/)

PS: Prebuild this page as HTML has a cost more higher in CPU cycles than keep dynamic for almost few users (composer don't access this page), this is done too for remove a layer of security problems, when nginx is exposed I don't need to think about PHP security problems, because I only have the worker.

**Pull request merged**
